Minor corrections to exercise instructions
ros-industrial/industrial_training pull request #308
Opened 2020-02-05 23:39 UTC by jrgnicho

Some minor changes to update/remove instructions

2020-02-06 14:10 UTC, marip8 requested changes

2020-02-06 14:10 UTC, marip8 commented on gh_pages/_source/session5/Simple-PCL-Interface-for-Python.rst
> +Most of the infrastructure for a ros node has already been completed for you; the focus of this exercise is the perception algorithms/pipeline. The `CMakelists.txt` and `package.xml` are complete and
Change `ros` to `ROS`

2020-02-06 14:10 UTC, marip8 commented on gh_pages/_source/session5/Simple-PCL-Interface-for-Python.rst
> +#. Open *CMakeLists.txt*. You can open the file in OT Creator (preferred) or PyCharm (or you can use nano, emacs, vim, or sublime). Uncomment line 19 or wherever you find "# catkin_python_setup() " a
Let's change the verbiage to something like "open the file in a text editor or IDE. Uncomment the line '# catkin_python_setup()` and save. I don't think there's any need to plug specific IDEs

2020-02-06 14:10 UTC, marip8 commented on gh_pages/_source/session5/Simple-PCL-Interface-for-Python.rst
> +   Note: PyCharm can be installed from the **Ubuntu Software** application.
Remove this line for same reason as above.

2020-03-28 01:25 UTC, Levi-Armstrong approved these changes

2020-03-28 01:26 UTC, Levi-Armstrong commented
CI is failing though

2020-07-10 14:36 UTC, marip8 approved these changes

2020-07-10 22:39 UTC, merged