Edits to training during to resolve build errors
ros-industrial/industrial_training pull request #313
Opened 2020-04-08 21:21 UTC by cbw36

2020-04-08 21:26 UTC, cbw36 commented on exercises/Perception-Driven_Manipulation/template_ws/src/robot_config/urdf/ur5.urdf.xacro
> -<robot xmlns:xacro="http://ros.org/wiki/xacro">
Was receiving the error: Undefined parameters [hw_interface] when instantiating macro: ur_arm_transmission.

To resolve the error, substituted the existing ur5.urdf.xacro with `universal_robot/ur_description/urdf/ur5.urdf/xacro`

2020-04-08 21:28 UTC, cbw36 commented on gh_pages/_downloads/ros-industrial-training-setup.sh
> -sudo apt install -y ros-melodic-perception ros-melodic-urdf-tutorials ros-melodic-moveit
The package `ros-melodic-urdf-tutorials` does not exist. The correct package name is `ros-melodic-urdf-tutorial`, but it is already installed as a dependancy on another package.

2020-04-08 21:32 UTC, cbw36 commented on gh_pages/_source/session4/Descartes-Path-Planning.md
> +    <launch>
Not sure if it is assumed the individual will know to include <launch></launch>

2020-07-09 21:15 UTC, marip8 requested changes

2020-07-09 21:15 UTC, marip8 commented on gh_pages/_source/demo1/Inspect-the-package.md
> +>Clone the ROS-I repo [universal_robot](https://github.com/ros-industrial/universal_robot) into the src directory of `perception_driven_ws`. Switch to the `melodic-devel` branch.
`kinetic-devel` is actually the default "master" branch of the UR repository. I would amend this to say:

>Clone the [universal_robot repository](https://github.com/ros-industrial/universal_robot) into the `src` directory of `perception_driven_ws`

2020-07-09 21:16 UTC, marip8 commented
@cbw36 we just removed the custom UR5 xacro from this exercise. Can you rebase this branch to remove those now-obsolete changes?

2020-07-10 16:39 UTC, cbw36 commented
Just pushed after rebasing my branch. Let me know if I need to change anything else

2020-07-10 22:44 UTC, marip8 commented
Can you completely remove the custom `ur5.urdf.xacro` file from this demo? It seems like we missed it in #315. We should edit the places where it is referenced by referencing the UR5 URDF from the official repository instead.

2020-07-17 15:49 UTC, marip8 approved these changes

2020-07-17 22:34 UTC, closed without merging