Update Training Material Request #318
ros-industrial/industrial_training pull request #321
Opened 2020-07-07 07:54 UTC by sachinkum0009

Update Training Material Request #318
Added the screenshots of Ubuntu 18.04 and editing as per requirements.

2020-07-07 08:33 UTC, sachinkum0009 commented
added touch command and updated the document and ready for the pull request.

2020-07-09 20:06 UTC, marip8 requested changes

2020-07-09 20:06 UTC, marip8 commented on gh_pages/_source/prerequisites/Navigating-the-Ubuntu-GUI.md
> +3. Notice that there are menu hightlights of the folder icon. The dots on the left show how many windows of this application are open. Clicking on these icons when the applications are open does one
Typo in `hightlights`; should be *highlights*

2020-07-09 20:06 UTC, marip8 commented on gh_pages/_source/prerequisites/The-Linux-Terminal.md
> +    * This will create a new Document named **"Untitiled Document"**
Typo in `Untititled`; should be *Untitled*

2020-07-09 20:09 UTC, marip8 commented
@sachinkum0009 are the images you added in this PR used anywhere in the markdown documentation? If not, we should consider including them in the appropriate places in the documentation or removing them (unless there is a compelling reason to have them in the repository but not the documentation)

2020-07-10 02:28 UTC, sachinkum0009 commented
Yes, the images added are used in the markdown file. You can review the changes.

2020-07-10 14:19 UTC, marip8 commented
I built the documentation, and I can see the new images. From the PR, they looked like new (opposed to modified existing) images and I didn't see where they were used in the diff.

2020-07-10 14:23 UTC, marip8 approved these changes

2020-07-10 15:21 UTC, merged

2020-07-10 15:21 UTC, marip8 commented
@sachinkum0009 thanks for the contribution

2020-07-10 15:41 UTC, sachinkum0009 commented
@marip8 it is my pleasure.